# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b45a479b716e50c2cbd8cbf7fb21204e06ce1e63318bfc3b08ead0af2631e6c0f5694cd2fe4e7cd7a5493dd17eac922f7ac90c2d235bcc6badce9907e383e9d

test:
  secret_key_base: 8281faca952020702aaf15150dad550516b39b7ed012d02e75515c564a03912a25d7ec846eb294fed6c6ce81f5366d2c662c08e7df74c27e746bde0578e34950

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
